### ISSUE TITLE
Failure when executing Amber/CoCo workflow on Blue BioU (Rice)

### ISSUE THREAD

**Issue by jp43** [radical-cybertools/ExTASY#106]
Here is what I get when setting export RADICAL_PILOT_VERBOSE=DEBUG (end of the message):

2014:11:27 22:47:20 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe50a208ed02a54967d9' state changed from 'StagingInput' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe50a208ed02a54967d9' state changed to PendingExecution.
2014:11:27 22:47:41 radical.pilot.MainProcess: [INFO    ] ComputePilot '5477fe4fa208ed02a54967d7' state changed from 'PendingActive' to 'Active'.
[Callback]: ComputePilot '5477fe4fa208ed02a54967d7' state changed to Active.
2014:11:27 22:47:41 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe50a208ed02a54967d9' state changed from 'PendingExecution' to 'Scheduling'.
[Callback]: ComputeUnit '5477fe50a208ed02a54967d9' state changed to Scheduling.
2014:11:27 22:47:41 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe50a208ed02a54967d9' state changed from 'Scheduling' to 'Executing'.
[Callback]: ComputeUnit '5477fe50a208ed02a54967d9' state changed to Executing.
2014:11:27 22:47:42 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe50a208ed02a54967d9' state changed from 'Executing' to 'Done'.
[Callback]: ComputeUnit '5477fe50a208ed02a54967d9' state changed to Done.
Starting Simulation
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967e7' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967e7' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967da' state changed from 'New' to 'Executing'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967da' state changed to Executing.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967dc' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967dc' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967df' state changed from 'New' to 'Scheduling'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967df' state changed to Scheduling.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967e8' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967e8' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967dc' state changed from 'PendingExecution' to 'Scheduling'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967dc' state changed to Scheduling.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967dd' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967dd' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967e2' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967e2' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967df' state changed from 'Scheduling' to 'Executing'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967df' state changed to Executing.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967e9' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967e9' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967e1' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967e1' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967e3' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967e3' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967e4' state changed from 'New' to 'PendingExecution'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967e4' state changed to PendingExecution.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] RUN ComputeUnit '5477fe6ea208ed02a54967da' state changed from 'Executing' to 'Failed'.
[Callback]: ComputeUnit '5477fe6ea208ed02a54967da' state changed to Failed.
#######################
#######################
ComputeUnit 5477fe6ea208ed02a54967da has FAILED. Can't recover.
ComputeUnit log: [u'Scheduled for execution on ComputePilot 5477fe4fa208ed02a54967d7.']
unit manager controller thread caught system exit -- forcing application shutdown
Execution was interrupted
Closing session, exiting now ...
2014:11:27 22:47:44 radical.pilot.MainProcess: [WARNING ] 'delete' flag on session is deprecated. Please use 'cleanup' and 'terminate' instead!
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] Sent 'COMMAND_CANCEL_PILOT' command to all pilots.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] ComputePilot '5477fe4fa208ed02a54967d7' state changed from 'Active' to 'Canceled'.
[Callback]: ComputePilot '5477fe4fa208ed02a54967d7' state changed to Canceled.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] Sent 'COMMAND_CANCEL_PILOT' command to all pilots.
2014:11:27 22:47:44 radical.pilot.MainProcess: [DEBUG   ] PilotManager.close(): PilotLauncherWorker-1 terminated.
2014:11:27 22:47:44 radical.pilot.MainProcess: [DEBUG   ] Worker thread (ID: Thread-1[4370481152]) for PilotManager 5477fe4fa208ed02a54967d6 stopped.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] Closed PilotManager 5477fe4fa208ed02a54967d6.
2014:11:27 22:47:44 radical.pilot.MainProcess: [DEBUG   ] Worker thread (ID: Thread-3[4393586688]) for UnitManager 5477fe50a208ed02a54967d8 stopped.
2014:11:27 22:47:44 radical.pilot.MainProcess: [INFO    ] Closed UnitManager 5477fe50a208ed02a54967d8.
2014:11:27 22:47:45 radical.pilot.MainProcess: [INFO    ] Deleted session 5477fe4fa208ed02a54967d5 from database.
2014:11:27 22:47:45 radical.pilot.MainProcess: [INFO    ] Closed Session 5477fe4fa208ed02a54967d5.

---------------
Here is what the radical pilot folder looks like:

-rw-r--r-- 1 52430 2006   16387 Nov 27 22:47 AGENT.LOG
-rw------- 1 52430 2006   19345 Nov 27 22:47 AGENT.STDERR
-rw------- 1 52430 2006   14283 Nov 27 22:47 AGENT.STDOUT
-rwxr-xr-x 1 52430 2006   14413 Nov 27 22:47 default_bootstrapper.sh
-rw-r--r-- 1 52430 2006  102705 Nov 27 22:47 radical-pilot-agent.py
drwxr-xr-x 2 52430 2006   65536 Nov 27 22:47 unit-5477fe50a208ed02a54967d9
drwxr-xr-x 2 52430 2006   65536 Nov 27 22:47 unit-5477fe6ea208ed02a54967da
drwxr-xr-x 2 52430 2006   65536 Nov 27 22:47 unit-5477fe6ea208ed02a54967db
drwxr-xr-x 2 52430 2006   65536 Nov 27 22:47 unit-5477fe6ea208ed02a54967dc
drwxr-xr-x 2 52430 2006   65536 Nov 27 22:47 unit-5477fe6ea208ed02a54967dd
drwxr-xr-x 2 52430 2006   65536 Nov 27 22:47 unit-5477fe6ea208ed02a54967df
drwxr-xr-x 2 52430 2006   65536 Nov 27 22:47 unit-5477fe6ea208ed02a54967e1
drwxr-xr-x 6 52430 2006   65536 Nov 27 22:47 virtualenv
drwxr-xr-x 8 52430 2006   65536 Nov 27 22:47 virtualenv-1.9
-rw-r--r-- 1 52430 2006 2004399 Nov 27 22:47 virtualenv-1.9.tar.gz

-----------------
The contents of the file STDERR in the unit folders (except for the first unit folder unit-5477fe50a208ed02a54967d9) is:

/bin/bash: line 0: -i: invalid shell option name
/bin/bash: line 0: -i: invalid shell option name

----------------
The contents of the file radical_*.sh in the unit folders (except for the first unit folder unit-5477fe50a208ed02a54967d9):

#!/bin/bash -l
cd /gpfs-biou/jp43/radical.pilot.sandbox/pilot-5477fe4fa208ed02a54967d7/unit-5477fe6ea208ed02a54967df
module load amber
cp /gpfs-biou/jp43/radical.pilot.sandbox/pilot-5477fe4fa208ed02a54967d7/unit-5477fe50a208ed02a54967d9/penta.crd min0.crd
cp /gpfs-biou/jp43/radical.pilot.sandbox/pilot-5477fe4fa208ed02a54967d7/unit-5477fe50a208ed02a54967d9/penta.top .
cp /gpfs-biou/jp43/radical.pilot.sandbox/pilot-5477fe4fa208ed02a54967d7/unit-5477fe50a208ed02a54967d9/min.in .

/opt/apps/openmpi/1.4.3-gcc/bin/mpiexec -n 2 -host c40,c40, /bin/bash "-O" "-i" "min.in" "-o" "min0.out" "-inf" "min0.inf" "-r" "md0.crd" "-p" "penta.top" "-c" "min0.crd" "-ref" "min0.crd"

-------------
In the first unit folder, radical_*.sh is:

#!/bin/bash -l
cd /gpfs-biou/jp43/radical.pilot.sandbox/pilot-5477fe4fa208ed02a54967d7/unit-5477fe50a208ed02a54967d9

/bin/echo "1"

**Comment by vivek-bala** [comment]
Will be tested when expanding mdkernels to support more resources.
