### ISSUE TITLE
Gromacs/LSDMap fail on STAMPEDE when start_iter=1 

### ISSUE THREAD

**Issue by ashkurti** [radical-cybertools/ExTASY#123]
After performing a round of testing with all default parameters, on the same folder, after changing the parameter of gromacslsdmap.wcfg: "start_iter=0" to "start_iter=1".

Log of extasy with active debug attached at: https://gist.github.com/ashkurti/2b335112751c10ef257d

**Comment by vivek-bala** [comment]
closing as outdated, please follow #145 .
