### ISSUE TITLE
'Failed to create backup...' message from COCO/Amber

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#129]
Running COCO/Amber on ARCHER, using latest release of radical-pilot (0.23), and master of mdkernels and extasy.  The workflow completed OK, but there were some errors reported in the output:

[Callback]: ComputeUnit '5490017fd7bf75d3786af507' state changed to StagingOutput.
[Callback]: ComputeUnit '5490017fd7bf75d3786af507' state changed to Done.
[Callback]: ComputeUnit '5490017fd7bf75d3786af508' state changed to StagingOutput.
[Callback]: ComputeUnit '5490017fd7bf75d3786af508' state changed to Done.
Simulation Execution Time :  96.254
Creating backup...
**Failed to create backup..**
Cycle : 2
Preprocessing stage ....
[Callback]: ComputeUnit '549001b5d7bf75d3786af50c' state changed to PendingExecution.
[Callback]: ComputeUnit '5490

This happens at the end of each and every cycle.  I uploaded the full debug log to https://gist.github.com/ibethune/64f70937babc31835dd9

**Comment by ibethune** [comment]
I can confirm that this is indeed fixed :)

**Comment by oleweidner** [comment]
Great - thanks for confirming.
