### ISSUE TITLE
Gromacs/LSDMap on ARCHER too slow

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#133]
Following the instructions, when using ARCHER the GROMACS Simulation part is expected to take ~250s and the LSDMap Analysis part ~30s.

According to tests by Elena and myself it is taking much longer than this, so that it is no longer possible to complete the example workflows within a reasonable time (like < 20 mins).

I re-ran with the smaller inputs provided by Vivek in ExTASY/sample_output_logs/grlsd-on-archer, and the output (removing the callbacks) is:

Cycle : 0
Preprocessing stage ....
Starting Simulation
Simulation Execution Time :  7397.411
Starting Analysis
Select + Reweighting step
Analysis Execution time :  39.23
Creating backup...
Cycle : 1
Preprocessing stage ....
Starting Simulation
Simulation Execution Time :  1967.503
Starting Analysis
Select + Reweighting step
Analysis Execution time :  31.533
Creating backup...
Closing session, exiting now ...

The LSDMap parts seem to be OK, but the GROMACS runs are very slow.  And oddly, the first cycle takes much longer.  Given that there are 24 CUs, and each execution is supposed to last around <100s (from Stampede), even if all the CUs are serialised due to ARCHER allowing only a single job per node at one time, something is wrong here!

The callbacks and logfile can be found here: https://gist.github.com/ibethune/0e7a2d020d335f0d810b

**Comment by oleweidner** [comment]
Can you confirm that this ticket can be closed?

**Comment by ibethune** [comment]
No (I thought I commented here this morning, but obviously not!), the problem still exists.  Can you post exactly the input files you are using for the jenkins Gromacs/LSDMap test on ARCHER and I will check it carefully against what I am using, and against the files linked from the tutorial

**Comment by ibethune** [comment]
OK, I found the problem.  The Jenkins test uses the input trajectory file https://raw.githubusercontent.com/radical-cybertools/ExTASY/devel/config_small/grlsd-on-archer/input.gro
 which has 100 snapshots in it.
I was using the one linked from the documentation https://raw.githubusercontent.com/radical-cybertools/ExTASY/devel/gromacs_lsdmap_example/input.gro, which has 1000 snapshots.

I propose that we use the smaller file for the example in the walkthrough, since the linked one takes too long.  With the smaller file I get the expect times of 200-250s for simulation and ~30s for analysis.

Also, I noticed there is an inconsistency in the gromacslsdmap.wcfg file.

In https://raw.githubusercontent.com/radical-cybertools/ExTASY/devel/config_small/grlsd-on-archer/gromacslsdmap.wcfg num_runs = 100
In https://raw.githubusercontent.com/radical-cybertools/ExTASY/master/config/gromacslsdmap.wcfg num_runs=1000
In https://github.com/radical-cybertools/ExTASY/blob/master/README.md (see section 3.1.1) num_runs=10000 and various other parameters are also different from the ones in the downloadable files.

I suggest that these all be changed to match the file in config_small.  If I'm not mistaken num_runs should be equal to or less than the number of actual configurations?

**Comment by vivek-bala** [comment]
Sorry about the delay. Was testing the new set of files on jenkins.

I have created/organized the config and input files separately, depending on the kernel and the target machine. Although most of them might be the same, I felt this avoids confusions.

Config files : https://github.com/radical-cybertools/ExTASY/tree/master/config_files
Input files : https://github.com/radical-cybertools/ExTASY/tree/master/input_files

Test : http://ci.radical-project.org/job/ExTASY/67/

I have updated the documentation to point to these files in each of the sections.

If this sounds good, I can remove config/ config_small/ to avoid confusion.

**Comment by vivek-bala** [comment]
4884e7253f9d4a0ce526027d2696f9a2c793ac19

**Comment by ibethune** [comment]
Seems OK, now I tried again with the new default files.
