### ISSUE TITLE
linked gromacslsdmap.wcfg file does not match documentation

### ISSUE THREAD

**Issue by CharlieLaughton** [radical-cybertools/ExTASY#140]
In the installation documentation at https://github.com/radical-cybertools/ExTASY/tree/devel#1-installation , the contents of the linked copy of the .wcfg file does not match what is shown in the documentation. For example the downloaded file has num_CUs = 16 while the documentation shows num_CUs = 64.

**Comment by ibethune** [comment]
NB. not just the num_CUs but also some of the other variables are different.  Please change them all to match the linked file (which is correct)

**Comment by vivek-bala** [comment]
There were a few more variables which I have changed in 67cd5d451ad2f3526d776df7e68ee253de2cc7ae. I can't seem to find any after this commit. Could you point me to the mismatch you are referring to ?

**Comment by ibethune** [comment]
Sorry, I had seen the pre-commit version.  I think this is all OK now.
