### ISSUE TITLE
GROMACS/LSDMap Analysis step fails on Stampede

### ISSUE THREAD

**Issue by CharlieLaughton** [radical-cybertools/ExTASY#141]
Trying to run the basic LSDMap/Gromacs example from my Mac to Stampede I get the following, reproducible, error. The Cycle 0 of the simulations finishes OK but then:
```
...
[Callback]: ComputeUnit '54c524699e3d0a32a6ef776e' state changed to Done.
[Callback]: ComputeUnit '54c524699e3d0a32a6ef776f' state changed to Done.
[Callback]: ComputeUnit '54c524699e3d0a32a6ef7770' state changed to Done.
Simulation Execution Time :  59.953
Starting Analysis
[Callback]: ComputeUnit '54c524b09e3d0a32a6ef7771' state changed to Executing.
[Callback]: ComputeUnit '54c524b09e3d0a32a6ef7771' state changed to Failed.
#######################
##       ERROR       ##
#######################
ComputeUnit 54c524b09e3d0a32a6ef7771 has FAILED. Can't recover.
ComputeUnit log: [<radical.pilot.logentry.Logentry object at 0x105d23150>]
Select + Reweighting step
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/Users/charlie/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 302, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/Users/charlie/ExTASY-tools/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 202, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/Users/charlie/ExTASY-tools/lib/python2.7/site-packages/radical/ensemblemd/extasy/bin/runme.py", line 52, in unit_state_change_cb
    print "STDERR : {0}".format(unit.stderr)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 301: ordinal not in range(128)

^CExecution was interrupted
Closing session, exiting now ...
[Callback]: ComputePilot '54c523ec9e3d0a32a6ef775e' state changed to Canceled.
```

**Comment by oleweidner** [comment]
This needs to be addressed in RADICAL-Pilot level. I have opened a ticket: https://github.com/radical-cybertools/radical.pilot/issues/479.

**Comment by marksantcroos** [comment]
The error seems to come from ensemblemd swallowing on something in the error output.
What would you expect from RP?

**Comment by andre-merzky** [comment]
Agree -- Ole, if you remember, we made the unit.stdout/stderr to support unicode -- that now seems what gets delivered in the unit callback.  Format switches to unicode only on unicode strings, ie:

```
-    print "STDERR : {0}".format(unit.stderr)
+    print u"STDERR : {0}".format(unit.stderr)
```

**Comment by oleweidner** [comment]
Possible fix implemented in 'devel'. Vivek, please review, merge and push out another RC.

**Comment by vivek-bala** [comment]
Done 41da5aa62d71c63cebcd04e1e0968b06a0e04afc. Updated docs.

**Comment by marksantcroos** [comment]
Real fix is something like?

``` python
print "STDERR : {0}".format(unit.stderr.encode('utf-8'))
```

**Comment by marksantcroos** [comment]
Besides the question what the format is adding here in the first place ...

**Comment by vivek-bala** [comment]
Hmmm, I don't understand the difference between the two. I tried with a simple implementation.

simple_bot.py : https://gist.github.com/vivek-bala/e9326ca05b917199ff88
CU executes -> test.py : https://gist.github.com/vivek-bala/8f0dd3e5f3d3fa70723b

Try 1: 

```
$ python simple_bot.py 
Initializing Pilot Manager ...
Submitting Compute Pilot to Pilot Manager ...
Initializing Unit Manager ...
Registering Compute Pilot with Unit Manager ...
Submit Compute Units to Unit Manager ...
Waiting for CUs to complete ...
[Callback]: ComputeUnit '54d3c5e52330e02156dbeae0' state changed to PendingInputStaging.
[Callback]: ComputeUnit '54d3c5e52330e02156dbeae0' state changed to StagingInput.
[Callback]: ComputePilot '54d3c5e12330e02156dbeade' state: Launching.
[Callback]: ComputeUnit '54d3c5e52330e02156dbeae0' state changed to PendingExecution.
[Callback]: ComputePilot '54d3c5e12330e02156dbeade' state: PendingActive.
[Callback]: ComputePilot '54d3c5e12330e02156dbeade' state: Active.
[Callback]: ComputeUnit '54d3c5e52330e02156dbeae0' state changed to Scheduling.
[Callback]: ComputeUnit '54d3c5e52330e02156dbeae0' state changed to Executing.
[Callback]: ComputeUnit '54d3c5e52330e02156dbeae0' state changed to Done.
ComputeUnit 54d3c5e52330e02156dbeae0 has FINISHED. 
All CUs completed successfully!
Closing session, exiting now ...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 302, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/home/vivek/Research/rp-test/local/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 202, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "simple_bot.py", line 47, in unit_state_cb
    print "STDOUT : {0}".format(unit.stdout)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u5000' in position 284: ordinal not in range(128)

[Callback]: ComputePilot '54d3c5e12330e02156dbeade' state: Canceled.
```

Try 2: 
```
- print "STDOUT : {0}".format(unit.stdout)
+ print u"STDOUT : {0}".format(unit.stdout)
```

```
$ python simple_bot.py 
Initializing Pilot Manager ...
Submitting Compute Pilot to Pilot Manager ...
Initializing Unit Manager ...
Registering Compute Pilot with Unit Manager ...
Submit Compute Units to Unit Manager ...
Waiting for CUs to complete ...
[Callback]: ComputeUnit '54d3c7e22330e0225c0ebae5' state changed to PendingInputStaging.
[Callback]: ComputeUnit '54d3c7e22330e0225c0ebae5' state changed to StagingInput.
[Callback]: ComputePilot '54d3c7de2330e0225c0ebae3' state: Launching.
[Callback]: ComputeUnit '54d3c7e22330e0225c0ebae5' state changed to PendingExecution.
[Callback]: ComputePilot '54d3c7de2330e0225c0ebae3' state: PendingActive.
[Callback]: ComputePilot '54d3c7de2330e0225c0ebae3' state: Active.
[Callback]: ComputeUnit '54d3c7e22330e0225c0ebae5' state changed to Scheduling.
[Callback]: ComputeUnit '54d3c7e22330e0225c0ebae5' state changed to Executing.
[Callback]: ComputeUnit '54d3c7e22330e0225c0ebae5' state changed to Done.
ComputeUnit 54d3c7e22330e0225c0ebae5 has FINISHED. 
STDOUT : 
=======================================================================

    Support for ~/.profile_user has been removed.
    See /usr/local/startup_scripts/transition.txt for remedies.

=======================================================================

倀

Execution was interrupted
Closing session, exiting now ...
[Callback]: ComputePilot '54d3c7de2330e0225c0ebae3' state: Canceled.
```

Try 3:
```
- print "STDOUT : {0}".format(unit.stdout)
+print "STDOUT : {0}".format(unit.stdout.encode('utf-8'))
```
```
$ python simple_bot.py 
Initializing Pilot Manager ...
Submitting Compute Pilot to Pilot Manager ...
Initializing Unit Manager ...
Registering Compute Pilot with Unit Manager ...
Submit Compute Units to Unit Manager ...
Waiting for CUs to complete ...
[Callback]: ComputeUnit '54d3c9cb2330e0231a27b052' state changed to PendingInputStaging.
[Callback]: ComputeUnit '54d3c9cb2330e0231a27b052' state changed to StagingInput.
[Callback]: ComputePilot '54d3c9c62330e0231a27b050' state: Launching.
[Callback]: ComputeUnit '54d3c9cb2330e0231a27b052' state changed to PendingExecution.
[Callback]: ComputePilot '54d3c9c62330e0231a27b050' state: PendingActive.
[Callback]: ComputePilot '54d3c9c62330e0231a27b050' state: Active.
[Callback]: ComputeUnit '54d3c9cb2330e0231a27b052' state changed to Scheduling.
[Callback]: ComputeUnit '54d3c9cb2330e0231a27b052' state changed to Executing.
[Callback]: ComputeUnit '54d3c9cb2330e0231a27b052' state changed to Done.
ComputeUnit 54d3c9cb2330e0231a27b052 has FINISHED. 
STDOUT : 
=======================================================================

    Support for ~/.profile_user has been removed.
    See /usr/local/startup_scripts/transition.txt for remedies.

=======================================================================

倀

Execution was interrupted
Closing session, exiting now ...
[Callback]: ComputePilot '54d3c9c62330e0231a27b050' state: Canceled.
```

Both methods seem to work with format in this example. Not sure why 
```print u"STDERR : ".format(unit.stderr)``` still produces this issue.

**Comment by vivek-bala** [comment]
Just want to make sure before I commit changes with 
```print "STDERR : {0}".format(unit.stderr.encode('utf-8'))```

**Comment by marksantcroos** [comment]
This test is too "reckless"! ;-)

**Comment by marksantcroos** [comment]
I think you can reproduce it by changing your test.py to something like:
``` python
print "倀"
```
I think the correct fix would be then:
``` python
print u"STDERR : {0}".format(unit.stderr.decode('utf-8'))
```

**Comment by vivek-bala** [comment]
I tried this, 
```
In [2]: k= "倀"

In [3]: print k
倀

In [4]: print "{0}".format(k)
倀
```

**Comment by vivek-bala** [comment]
@CharlieLaughton could you please login to Stampede and check what the error actually is in
```$WORK/radical.pilot.sandbox/54c523ec9e3d0a32a6ef775e/54c524b09e3d0a32a6ef7771``` ? I cannot reproduce an error with grlsd on stampede, so I can't have a look at this possible error.

**Comment by CharlieLaughton** [comment]
Hi Vivek,

I had deleted that directory but I have re-run the job with exactly the same result.

The offending unit-* directory contains the following files:

login1.stampede(21)$ ls
config.ini      radical_pilot_cu_launch_script-Ynjg4g.sh  STDOUT
lsdm.py         run_analyzer.sh                           tmp.gro
pre_analyze.py  STDERR                                  tmpha.gro

The contents of STDERR reveal the error. After an apparently successful run of the gromacs “trjconv” program, things go wrong:

….
Inactive Modules:
  1) gromacs

The following have been reloaded with a version change:
  1) intel/13.0.2.146 => intel/14.0.1.106  2) mvapich2/1.9a2 => mvapich2/2.0b


The following have been reloaded with a version change:
  1) python/2.7.3-epd-7.3.2 => python/2.7.6

Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
  File "lsdm.py", line 13, in <module>
  File "lsdm.py", line 13, in <module>
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
  File "lsdm.py", line 13, in <module>
Traceback (most recent call last):
  File "lsdm.py", line 13, in <module>
    from lsdmap.util import metric as mt
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
    from lsdmap.util import metric as mt
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
  File "/home1/03036/jp43/.local/lib/python2.7/site-packages/lsdmap/util/metric.p
y", line 5, in <module>
        import pyqcprot
import pyqcprot
    import pyqcprot
    import pyqcprot
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
    import pyqcprot
      File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/py
qcprot.c:7440)
import pyqcprot
    import pyqcprot
    import pyqcprot
    import pyqcprot
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
      File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/py
qcprot.c:7440)
import pyqcprot
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
    import pyqcprot
    import pyqcprot
    import pyqcprot
    import pyqcprot
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
    import pyqcprot
    import pyqcprot
    import pyqcprot
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
  File "__init__.pxd", line 155, in init lsdmap.util.pyqcprot (lsdmap/util/pyqcpr
ot.c:7440)
ValueErrorValueErrorValueErrorValueErrorValueErrorValueErrorValueErrorValueError:
 : : : : : : numpy.dtype has the wrong size, try recompilingnumpy.dtype has the w
rong size, try recompilingnumpy.dtype has the wrong size, try recompilingnumpy.dt
ype has the wrong size, try recompiling



numpy.dtype has the wrong size, try recompilingnumpy.dtype has the wrong size, tr
y recompiling
numpy.dtype has the wrong size, try recompiling

ValueErrorValueError: : ValueErrorValueError: : ValueError: ValueErrornumpy.dtype
 has the wrong size, try recompilingnumpy.dtype has the wrong size, try recompili
ngValueErrornumpy.dtype has the wrong size, try recompiling: numpy.dtype has the
wrong size, try recompiling

…(etc.)



The problem seems to have something to do with numpy, I guess?

Let me know what I can do to help.

Charlie

**Comment by CharlieLaughton** [comment]
I have - maybe - found the source of the error. In my .bashrc file on Stampede I have commands that tweak my PYTHONPATH and PATH variables to pick up CoCo. It seems these are causing clashes with the gromacs-lsdmap workflow: if I remove these PATH adjustments the job runs fine.

This is still an issue though - the ExTASY workflows need to be insulated from this sort of thing, because we cannot entirely prescribe the user's environment.

**Comment by vivek-bala** [comment]
Hmm, one way I can think of is that we can reset (unset,set) the environment variables similar to how on startup RP does a module purge. Not sure if that is the way to go around bashrc configs. @oleweidner ?

I am not sure if RP or ExTASY should be insulated from bashrc configs since in our discussion about extending this to machines beyond Stampede and Archer, one of the suggested methods was to expect the user to have required configs (module loads, path variables) set in the bashrc in the targetted system. (the second was to have the user make an entry in mdkernels).

**Comment by CharlieLaughton** [comment]
This is indeed not a simple issue.

I think we need to go one way or the other – at the moment we are somewhere in the middle. I would suggest that the only scalable solution is to make the user responsible for making the key kernels work satisfactorily on the target machine. But at the moment that is not happening – nowhere do we tell the user what LSDMap-related commands need to, in effect, run without complaint if executed from the command line in their usual login environment. In this particular case the python script “lsdm.py” will not run if it picks up the wrong version of the numpy library – which it may if a user has something specific in their .bashrc file or similar.

However, for ExTASY 0.1 it may be better to go down the route of a module and PATH purge process at initialisation – not scalable, but a simpler solution for just two platforms (ARCHER and Stampede) maybe.

**Comment by vivek-bala** [comment]
@CharlieLaughton, I have added the path purge method in mdkernels. Could you test again please ?
I have the method in a separate branch so please use ```pip install --upgrade git+https://github.com/radical-cybertools/radical.ensemblemd.mdkernels.git@temp/purge_bash#egg=radical.ensemblemd.mdkernels ``` to install mdkernels.

**Comment by CharlieLaughton** [comment]
Hi Vivek,

Just as soon as I have some SUs on Stampede I’ll give it a go!

Cheers,

Charlie

**Comment by CharlieLaughton** [comment]
Hi Vivek,

No luck I’m afraid, the job fails with the same error. I checked the folders on Stampede and can confirm that the modules were purged and that Jordane’s directories are prepended to PATH and PYTHONPATH, but to no avail. If I change my .bashrc file back so I do not set any $PYTHONPATH myself, it runs fine. I suggest therefore that, for the purposes of this workflow, it is apparently unnecessary to include in the PYTHONPATH anything else other than Jordane’s directories, i.e. In lsdmap.json just do:

"export PYTHONPATH=/home1/03036/jp43/.local/lib/python2.7/site-packages”

Cheers,
Charlie

**Comment by vivek-bala** [comment]
Made the suggested change in mdkernels.

**Comment by CharlieLaughton** [comment]
It works!
