### ISSUE TITLE
if (num_cores_per_sim > PILOTSIZE) for lsdmap/gromacs on ARCHER

### ISSUE THREAD

**Issue by ebreitmo** [radical-cybertools/ExTASY#142]
On purpose I chose num_cores_per_sim = 25 > PILOTSIZE = 24.
The job just died after it ran out of wall clock time. Presumably RP is hanging waiting for 25 cores to become available?

it should be fixed (not urgent).

**Comment by vivek-bala** [comment]
I think this is an invalid condition. If pilotsize=24, only 24 cores are acquired. This would mean the maximum number of cores for any simulation/analysis stage is 24. We could add a flag to check if the entered value for num_cores_per_sim <= PILOTSIZE. Is that what you were referring to ?

**Comment by ibethune** [comment]
Yes, this is just an input validation check required.

**Comment by vivek-bala** [comment]
Added check condition in 4562615bc0cf6c4b682a23f078468aeb0425e0e6
