### ISSUE TITLE
Gromacs/LSDMap fails on STAMPEDE when start_iter=1 

### ISSUE THREAD

**Issue by ashkurti** [radical-cybertools/ExTASY#145]
The execution with the debug mode ON lasts for approx. 1 hour (I think the wall time is exceeded).

extasy log at:

https://gist.github.com/ashkurti/c2954400860aade86a9e

**Comment by ashkurti** [comment]
The execution refers to default files for the gromacs/lsdmap workflow with the only change that start_iter=1 and num_iterations=5 so as to have in the backup folder info on the iter4 as well. This context was run after performing a run with the default input files.

**Comment by vivek-bala** [comment]
Hmm.. I thought I had commented here. You have set the walltime to 60 mins. The pilot gets cancelled because execution goes beyond 60 mins.

```
2015:02:09 11:54:18 radical.pilot.MainProcess: [INFO    ] ComputePilot '54d89f70f8cdba39bcb6abbb' state changed from 'PendingActive' to 'Active'.
..
..
2015:02:09 12:54:19 radical.pilot.MainProcess: [ERROR   ] SAGA job state for ComputePilot 54d89f70f8cdba39bcb6abbb is Canceled.
```

**Comment by ashkurti** [comment]
Now, I am retrying this context following this procedure:

- Perform an extasy run with the default gromacs/lsdmap workflow files (this run is successful);
- Delete the following files: gromacslsdmap.wcfgc, stampede.rcfgc
- Move /backup/iter2 to /backup/old_iter2
- Change the start_iter parameter of gromacslsdmap.wcfg from 0 to 1(but keep the num_iterations parameter to 3 as per default).
- Activate debugging environment variables
- Run the extasy workflow.

After approx. 9 minutes the workflow ends up with the following error:
```
2015:02:16 12:41:38 radical.pilot.MainProcess: [ERROR   ] Couldn't call callback function 'ascii' codec can't encode character u'\xe4' in position 303: ordinal not in range(128) ...
```

extasy log at: https://gist.github.com/ashkurti/15c0b70d1f2c2036302d

**Comment by ashkurti** [comment]
I have made the radical pilot folder for this use-case context, publicly accessible. If anybody wants to browse through the files they are at /work/02998/ardi/radical.pilot.sandbox/pilot-54e1e34af8cdba4780931d98

**Comment by vivek-bala** [comment]
I think start_iter should always be a multiple of nsave. Since nsave was set to 2 in the first trial, start_iter should be 2 in the second and hence I would expect it to fail. The restart mechanism needs to be revisited again since we might not require to store 'paths' as it was discussed in the email that start_iter in the second trial will be the last iteration of the first trial (start_iter(2nd trial) = num_iterations(1st trial). I will try to update it over the weekend.

**Comment by ashkurti** [comment]
I have tried again setting start_iter to 2 but the pilot has failed again. Browsing through the radical pilot folders of the failing unit in Stampede I noticed the following error which I think relates to a mismatch of the expected and effective number of elements of the weights structure, as it has extensively been discussed before. 
The folder on stampede is public and can be accessed at /work/02998/ardi/radical.pilot.sandbox/pilot-54edc3b7f8cdba57fa46fca

```
Traceback (most recent call last):
  File "lsdm.py", line 384, in <module>
    LSDMap().run()
  File "lsdm.py", line 320, in run
    weights_thread = np.array([self.weights[idx] for idx in self.idxs_thread])
IndexError: index out of bounds
[cli_15]: aborting job:
```

**Comment by vivek-bala** [comment]
Please test restart cases again using master. Info on restart conditions/requirements is also added to the documentation.

**Comment by ashkurti** [comment]
This works for me now! :+1:
