### ISSUE TITLE
Version reporting 

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/ExTASY#147]
It would be good if the ExTASY tool would print the installed version + git tag before the execution starts, i.e., something like:
```
0.2-1-fhdgcejfjt
```
There's similar code in most of the other RADICAL projects, like for example in EnsembleMD: https://github.com/radical-cybertools/radical.ensemblemd/blob/master/setup.py#L33 - I think this could easily be adopted. 

This would be quite beneficial for debugging as it would allow us to detect the use of an outdated version right away. One might also want to consider to add a logging facility to the next version of ExTASY, but for now a simple 'print' should do the trick.

**Comment by vivek-bala** [comment]
done in devel.
