### ISSUE TITLE
Amber/Coco on STAMPEDE extasy version: 0.1.3.1-beta-8-gf8ad235

### ISSUE THREAD

**Issue by ashkurti** [radical-cybertools/ExTASY#150]
A failure on stampede occurs, log at: https://gist.github.com/ashkurti/7cdb8000f20d891fd88e

The radical.pilot folder is public at: /work/02998/ardi/radical.pilot.sandbox/pilot-5513e3c1f8cdba2f5608b8f7

A first impression shows a problem on finding the files from the staging area in the local machine: https://gist.github.com/ashkurti/7cdb8000f20d891fd88e#file-gistfile1-txt-L1795

```
2015:03:26 10:48:12 radical.pilot.MainProcess: [ERROR   ] DoesNotExist: file copy failed: mput  "/users/ardita/coam-on-stampede_26Mar_2/penta.crd" "/work/02998/ardi /radical.pilot.sandbox/pilot-5513e3c1f8cdba2f5608b8f7/staging_area/iter0/penta.c rd"
Uploading /users/ardita/coam-on-stampede_26Mar_2/penta.crd to /work/02998/ardi/radical.pilot.sandbox/pilot-5513e3c1f8cdba2f5608b8f7/staging_area/iter0/penta.crd
Couldn't get handle: No such file or directory
```
Above I can notice the introduction of a few blank spaces in the path of the folders on stampede...

I have also noticed this: https://gist.github.com/ashkurti/7cdb8000f20d891fd88e#file-gistfile1-txt-L22 (the redis module failed to be loaded) - this is for completion I do not know the functionality of this module in the saga layer though.

**Comment by ashkurti** [comment]
Similar as Issue #149

**Comment by vivek-bala** [comment]
The error seems to be in https://github.com/radical-cybertools/ExTASY/blob/master/src/radical/ensemblemd/extasy/bin/Simulator/Amber/simulator.py#L126-L128. A CU from cu_list_b is executed as soon as there is a slot available. This needs to be changed so that cu_list_b[i] is executed only after cu_list_a[i].

**Comment by ashkurti** [comment]
The tests are stuck due to the following error (have tried this several times) while installing radical pilot:
```
[ExTASY-tools] ardita@poirot 276% pip install --upgrade git+https://github.com/radical-cybertools/radical.pilot.git@master#egg=radical.pilot
Downloading/unpacking radical.pilot from git+https://github.com/radical-cybertools/radical.pilot.git@master
  Cloning https://github.com/radical-cybertools/radical.pilot.git (to master) to ./ExTASY-tools/build/radical.pilot
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/radical-cybertools/radical.pilot.git/info/refs

fatal: HTTP request failed
  Complete output from command /usr/bin/git clone -q https://github.com/radical-cybertools/radical.pilot.git /users/ardita/ExTASY-tools/build/radical.pilot:
  
----------------------------------------
Command /usr/bin/git clone -q https://github.com/radical-cybertools/radical.pilot.git /users/ardita/ExTASY-tools/build/radical.pilot failed with error code 128 in None
Storing complete log in /users/ardita/.pip/pip.log
```

**Comment by vivek-bala** [comment]
This could have been something temporary. Installing with the same pip install --upgrade worked for me now.

Although if I access https://github.com/radical-cybertools/radical.pilot.git/info/refs, I get

```
Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
```

**Comment by ashkurti** [comment]
Yes, it is true that sometimes it works - ex. the test is running at this moment. But I thought I'd rather mention this, since it was verified several times also over last week, these errors would appear randomly ... and block the rest of the procedure ...
