### ISSUE TITLE
Amber/Coco on STAMPEDE extasy version: 0.1.3.1-beta-14-g7c361ec

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/ExTASY#151]
Three cycles are completed but fourth never finishes. Last output I see is:
```
Simulation Execution Time :  52.603
Closing session, exiting now ...
[Callback]: ComputePilot '5516077723769c1e72a9ee5b' state changed to Canceled. 
```
Since num iterations is 4 I guess this is a fail? [extasy.log](https://raw.githubusercontent.com/AntonsT/various-things/master/extasy_logs/extasy-coco-amber-stampede.log)

**Comment by vivek-bala** [comment]
Cycle starts from 0, so I think this fine. I see 4 iter(0...3) folders in the staging_area.
