### ISSUE TITLE
COCO/Amber CU failed due to I/O error during output staging

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#156]
I have seen several errors of this sort this morning, where a CU fails due to an error during the output staging step.  The log contains a message like:

2015:03:30 12:02:25 radical.pilot.MainProcess: [DEBUG   ] flush: [   14] [     ] (flush pty read cache)
2015:03:30 12:02:25 radical.pilot.MainProcess: [DEBUG   ] flush: [   18] [     ] (flush pty read cache)
2015:03:30 12:02:25 radical.pilot.MainProcess: [DEBUG   ] write: [   18] [  119] ( ls /work/e290/e290/e290ib/radical.pilot.sandbox/pilot-55192c88d7bf75a56b1d81fa/unit-55192d32d7bf75a56b1d8206/md0.ncdf\n)
2015:03:30 12:02:25 radical.pilot.MainProcess: [DEBUG   ] read : [   18] [  157] ( ls /work/e290/e290/e290ib/radical.pilot.sandbox/pilot-55192c88d7bf75a56b1 ^Hd81fa/unit-55192d32d7bf75a56b1d8206/md0.ncdf\nCouldn't send packet: Broken pipe\n)
2015:03:30 12:02:25 radical.pilot.MainProcess: [ERROR   ] Output transfer failed: read from process failed '[Errno 5] Input/output error' : (B/s   --:-- ETA/home/h012/ibethune/testcoco11/penta.crd      100% 2165     2.1KB/s   00:00
sftp>  ls /work/e290/e290/e290ib/radical.pilot.sandbox/pilot-55192c88d7bf75a56b1 ^Hd81fa/unit-55192d32d7bf75a56b1d8206/md0.ncdf
Couldn't send packet: Broken pipe

Full set of logs, and the pilot directory are in /work/e290/e290/shared/iain/io-error/ on ARCHER

**Comment by vivek-bala** [comment]
Might be the same as one of the old tickets for archer. I believe the fix was to set $HOME/saga.cfg as

```
[saga.utils.pty]
ssh_share_mode = no
```

**Comment by ibethune** [comment]
Should that go into $HOME on the box where 'extasy' is run, or on the execution machine?

**Comment by vivek-bala** [comment]
This would be on the local machine (laptop/vm), where extasy is run.

**Comment by ibethune** [comment]
Thanks, but no, that doesn't solve the problem in this case.

**Comment by andre-merzky** [comment]
Iain -- please note that should be `$HOME/.saga.cfg` -- ie. a dot-file...

**Comment by ibethune** [comment]
Ah OK, I will try again with that!

**Comment by oleweidner** [comment]
Is this documented somewhere in the ExTASY docs and if so, does the documentation show the "dot"-file correctly?

**Comment by ibethune** [comment]
Closing, fixes by the .saga.cfg file (or env var)
