### ISSUE TITLE
ExTASY continues upon failure

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/ExTASY#158]
Even though a module couldn't be loaded, the execution continues:

```
An error occurred: No module named mdkernels
Closing session, exiting now ...
[Callback]: ComputePilot '551a6a9d6bf88ba6260c0412' state changed to Launching.
```

This might be a combination of an ExTASY and RP problem though?

**Comment by vivek-bala** [comment]
I think this is a unique case when the callback gets registered before the session.close() gets called at ```https://github.com/radical-cybertools/ExTASY/blob/devel/src/radical/ensemblemd/extasy/bin/runme.py#L214```.

**Comment by vivek-bala** [comment]
ExTASY terminates after the above callback (might take sometime though). It prints the callback, since the callback is executed before the session close. Added an import test now to avoid this.
