### ISSUE TITLE
/fs4 referred to directly in ARCHER shared virtualenv

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#171]
I noticed that the VIRTUAL_ENV variable in the ARCHER shared virtualenv is set to /fs4/e290/shared/shared_pilot_ve_20150429

This should really be /work/e290 for futurue proofing as the /fs4/ designation is potentially subject to change.  /work/e290 is the canonical directory name.

If easy / non-disruptive to fix we should do it now, if not in the run-up to 0.2 release.

**Comment by andre-merzky** [comment]
I'll move this ticket to radical-pilot, as we maintain the VE on that level.  Thanks for the note, we were not aware that the mountpoints are potentially changing.  I would propose that we set up a new VE in the RP devel branch, so that it gets tested, and activate it then with the next RP release (end of month),  ok?

**Comment by ibethune** [comment]
Sounds good.  I think the likelihood of them changing is very low (although it could happen as a result of the ongoing filesystem troubles).  The intention was that users never need to know or care which FS they are using, we should just refer to /work

**Comment by marksantcroos** [comment]
@andre-merzky Either I am missing the point, or this is already the case, see:
https://github.com/radical-cybertools/radical.pilot/blob/master/src/radical/pilot/configs/epsrc.json#L24

What you might see is a directory name that has been normalized at run time, which is ok I guess.

> we were not aware that the mountpoints are potentially changing

So as I would disagree with this statement too ;-)

**Comment by ibethune** [comment]
OK if that is the case, then I think we are all good - thanks for confirming!

**Comment by andre-merzky** [comment]
Thanks Mark! :)
