### ISSUE TITLE
Support pyCoCo -s flag in ExTASY 0.1.1

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#181]
Add a new variable to the .wcfg file, which is passed on to pyCoCo as the -s argument.  Ardita please comment on the ticket about what this should be called, and the explanitory text you want in the file.

**Comment by ashkurti** [comment]
The "-s" , "--selection" flag refers to an optional atom selection string that enables pyCoCo to work only on a subset of the biomolecular system. For example if the argument is "-s protein" the potential solvent in the system will be ignored and only the protein part of it will be considered for further analysis with pyCoCo.

**Comment by ashkurti** [comment]
Is this issue similar to #173 ?

**Comment by vivek-bala** [comment]
added in devel
