### ISSUE TITLE
Check that kernels needed by the workflows are working during startup

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#185]
At the start of the example workflows, call the sanity check method on each of the kernels that workflow will need, and fail if they are not working.

**Comment by vivek-bala** [comment]
It would be useful to have parameters for lsdmap and coco that would print the version. I'm addressing this ticket for gromacs and amber by printing their version numbers (if environment is set up), or an error (if not). The same can be done for LSDMap and CoCo

**Comment by TensorDuck** [comment]
This can be implemented. I guess either or both, we can do:

1. Make a variable so when you import the LSDMap module, you can do say, lsdmap.__version__ and it will print out the version number. 

2. Make an argparse command like --version. If It sees that flag at run, it will just print out the version and then exit. 

Both, or one of those can be implemented, but we should keep it uniform with COCO. Let us know.

**Comment by ashkurti** [comment]
Please not that there is a new tag now for pyCoCo - coco-0.10 - where the option for version detection is available through:

pyCoCo -V  
or
pyCoCo --version

Let me know whether this is useful for the checks.

@TensorDuck - if you could also implement version detection in LSDMap with same parameters that would be uniform I assume.

**Comment by TensorDuck** [comment]
This is implemented in v2.3 on sourceforge.

**Comment by vivek-bala** [comment]
added another argument "--Rcheck" that will ONLY CHECK for the specific package mentioned in the kernel config file on the machine specific in the resource config file. A process is launched which prompts the version of that packaged installed (mostly by the --version option) and returns the output/err to the user.

**Comment by TensorDuck** [comment]
Vivek, I forgot to ask, is v2.3 of dmdmd on Stampede or Archer yet?
