### ISSUE TITLE
ExTASY 0.2 docs - mongodb

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#200]
In section 2 of the docs we described how to set up a mongodb install.  I would add two things:

Advertise the extasy MongoDB (mongodb://extasy:extasyproject@extasy-db.epcc.ed.ac.uk/radicalpilot), which is available for trial usage only.  For production simulations we recommend they set up their own...

Also, nowhere I think do we say that you need to set the RADICAL_PILOT_DBURL variable.  At least I didn't and got an error when I ran the multiple_simulations_single_analysis.py script

**Comment by vivek-bala** [comment]
Examples need to specify the db url in the script.

**Comment by vivek-bala** [comment]
> Advertise the extasy MongoDB (mongodb://extasy:extasyproject@extasy-db.epcc.ed.ac.uk/radicalpilot), which is available for trial usage only. For production simulations we recommend they set up their own...

This is now added.

> Also, nowhere I think do we say that you need to set the RADICAL_PILOT_DBURL variable. At least I didn't and got an error when I ran the multiple_simulations_single_analysis.py script

I have added the db url in the example scripts. I don't think we want to expose the user to that. I think it would be better to ask the user to use the database_url parameter in the singleclusterenviornment.

**Comment by ibethune** [comment]
Thanks!
