### ISSUE TITLE
ExTASY 0.2 examples should be a little more verbose

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#203]
If you run the multiple_simulations_single_analysis.py script without RADICAL_ENMD_VERBOSE=info st, the script is totally silent. Please add some comments so the user can see that the script is progressing.  The current docs say:

"Run this example with RADICAL_ENMD_VERBOSE set to info if you want to see log messages about simulation progress"

In my view, this should say "if you want to see low-level debug logging information" - we shouldn't rely on info below the level of abstraction the user is working at to tell them what is going on.

**Comment by andre-merzky** [comment]
We started to use a Reporter class in RP, for the same purpose, to show progress in example scripts and applications.  That is not yet merged, and will only appear in 0.37 (which is due before tutorial though), but you may already want to look at it.  Here is an example using it:

radical-cybertools/radical.pilot/blob/feature/docs_am/examples/getting_started_local.py

It needs the `feature/demo` branch of radical.utils

**Comment by andre-merzky** [comment]
PS.: I should have mentioned that this needs `RADICAL_PILOT_VERBOSE=DEMO`  to show anything useful.  We consider making that the default level.

**Comment by vivek-bala** [comment]
Implemented in enmd RC0. Would be pushed to master and released soon.

**Comment by ibethune** [comment]
With RADICAL_ENMD_VERBOSE=REPORT this is now working fine, need to update the docs to reflect this.

**Comment by andre-merzky** [comment]
FWIW, in the RP examples, we use

```
os.environ['RADICAL_VERBOSE=REPORT']
```

in the top of the scripts.  That has its own pitfalls (overwrites other levels set before), but the examples then by default have a decent output...
