### ISSUE TITLE
ExTASY 0.2 docs: list of possible 'resource' strings

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#204]
In section 4.1.2 of the docs, the examples of "xsede.stampede" is given as a remote resource - can we also have a list (or link to a list) of possible values that can be used, and how to configure your own resource if you don't have access to one of the predefined ones?

**Comment by andre-merzky** [comment]
http://radicalpilot.readthedocs.org/en/latest/machconf.html#preconfigured-resources might help (but needs updating).  Also the list of resources supported in extasy may be different / need other configs, too?

**Comment by ibethune** [comment]
I think that's the right info.  In ExTASY 0.2 we are not making any guarantee that all of the tools required by the example workflows are installed.

**Comment by vivek-bala** [comment]
We currently have ``` how to configure your own resource``` in 8.2. But it makes more sense to pull the docs page from rp.

**Comment by vivek-bala** [comment]
added to docs
