### ISSUE TITLE
Instruction about loop-back SSH key on ARCHER

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#215]
In section 2.2.2 of ExTASY RTD we explain how to set up passwordless SSH to the remote machine.  We should add a note for ARCHER, that you also need to add a key to allow passwordless loopback SSH.  There is an RP FAQ on this, so we can just link to it: http://radicalpilot.readthedocs.org/en/latest/faq.html#avoid-the-error-permission-denied-publickey-keyboard-interactive-in-agent-stderr-or-stderr

Several people fell over this in the tutorial (despite me warning them up-front about it).

Is there any reason (other than RP being well-behaved?) that we can't do this automatically?

**Comment by vivek-bala** [comment]
This is discussed in 10.3: http://extasy.readthedocs.org/en/latest/pages/trouble.html#error-permission-denied-publickey-keyboard-interactive-in-agent-stderr.

> Is there any reason (other than RP being well-behaved?) that we can't do this automatically?

Not sure if we would want to do this as part of the agent. @andre-merzky @marksantcroos  ?

**Comment by marksantcroos** [comment]
> Is there any reason (other than RP being well-behaved?) that we can't do this automatically?

We discussed it at some point and didn't want to make it a universal action.

Main reason is that it will require quiet some logic to get right and bullet proof and the potential to lock people out of their accounts when things gone wrong.

So my preference would still be to make it a documentation item I think.

**Comment by ibethune** [comment]
OK that's fine, let's just do the doc fix.

**Comment by ibethune** [comment]
Don't fix, too system specific to go into the main text of the documentation.
