### ISSUE TITLE
Retrieving data from LSDMap/Gromacs workflow

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#216]
In AMBER/COCO we have a reasonable set of output files produced at the end of the run (coco log file and some trajectories).  We should add this for Gromacs/LSDMap too Justin or Eugen should be able to advise on what the right files to bring back are.

Some people tried this workflow at the tutorial and were wondering where the output was.  Looking for it in the RP sandbox is not good enough.

**Comment by vivek-bala** [comment]
> Some people tried this workflow at the tutorial and were wondering where the output was. Looking for it in the RP sandbox is not good enough.

The gromacs-lsdmap script should download the lsdmap.log file, weight file and the .gro file at the end of the specified iteration. https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/extasy_gromacs_lsdmap_loop.py#L165-L167. Was that not the case ?

I'll wait for Justin, Eugene to specify if any other files are to be downloaded as well.

**Comment by euhruska** [comment]
The output for lsdmap are the .ev files (the dimension reduced coordinates for every structure in the .gro file).

**Comment by TensorDuck** [comment]
Currently, I get the output files that Vivek specifies. I think people would like the .ev and .eg files at the end of every iteration so there's no reason to not save those as well, unless people are concerned about data storage. What side should that be fixed on? Our code on sourceforge or the code with extasy?

**Comment by vivek-bala** [comment]
Just fixed this now. Both .ev and .eg files will be downloaded.
