### ISSUE TITLE
Update to gromacs/5.1 on ARCHER

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#218]
gromacs/5.0.0 was dropped during the last maintenance session in favour of gromacs/5.1.  'module load gromacs' will give you 5.1 as a default.

Please update the kernel definitions so this works again (Elena reports it is currently broken), and if any changes are needed to the gromacs input files, check with the Rice team.

**Comment by vivek-bala** [comment]
changed in both master and devel.
