### ISSUE TITLE
Can one select which atoms are used in computing the RMSD for LSDmap?

### ISSUE THREAD

**Issue by dotsdl** [radical-cybertools/ExTASY#220]
I am trying out LSDmap directed MD for my own simulation systems, which include explicit solvent. In editing the various configuration files I didn't see any way of setting the atoms on which RMSDs should be calculated. Is there an easy way to do this? If not, what's the best way to go about it given the rest of the framework?

**Comment by TensorDuck** [comment]
The lsdmap framework should already be removing all solvents and protein hydrogen atoms, leaving only the heavy atoms in the pre-analyze step. Mainly, if you see in the `misc_files/pre_analyze.py` that runs the `trjconv` command for gromacs. If you want to change this, you can change the `echo 2` to `echo X` where X corresponds to the gromacs option you want for `trjconv`.  This should work by changing the helper scripts in that folder locally, correct me if I'm wrong Vivek.

If you want to check, you can run one iteration, and look at the second to last unit folder, which should contain the lsdmap results (.eg and .ev files) along with the input file for lsdmap analysis (tmpha.gro).

**Comment by dotsdl** [comment]
Ah, thanks. Now I see it.

Somewhat related, though happy to make another issue for it: where is the installation of gromacs (or the module on stampede) specified? We usually compile our own builds, and I'd like to know where to place the path to my gromacs binaries to use them.

**Comment by TensorDuck** [comment]
My understanding is that the radical team handles the installation of the packages and when using the extasy framework, you end up using those preinstalled packages. Perhaps Vivek would be best to answer that in a separate issue.

**Comment by TensorDuck** [comment]
Vivek: 
One thing that Iain brought to my intention is that we should avoid having the users look inside the pilot directories for checking outputs. Perhaps we should add copying tmpha.gro (as well as the .ev and .eg outputs) to the backup directory?

**Comment by dotsdl** [comment]
Nevermind, I found it. Since the `radical.ensemblemd` `Kernel` used is `md.gromacs`, the information for which module to use to set up the environment is contained in that call. I'll set up my own `Kernel` configuration to use our own build.

**Comment by vivek-bala** [comment]
@dotsdl Although editing the specific gromacs file within the ensemblemd package would work, it would be easier for the user to write one's own application kernel (http://extasy.readthedocs.org/en/latest/pages/develop.html#writing-new-application-kernels). The kernels provided with ensemble md are only for the example scripts. 

@TensorDuck the .ev and .eg files should be copied back to the user machine (based on the "nsave" value specified in the config file). Any file to be copied back can be specified in the user script using the "download_output_data" property of the kernels.
