### ISSUE TITLE
ENMD scripts are silent by default

### ISSUE THREAD

**Issue by ibethune** [radical-cybertools/ExTASY#225]
Using the latest enmd from master, the scripts are silent unless RADICAL_ENMD_VERBOSE=Report is exported.  I thought the default behaviour was to use this level of verbosity unless the users specified otherwise?

```
mbp-ib:grlsd-on-archer ibethune$ RADICAL_ENMD_VERBOSE=Report python 
... SILENCE...
... I killed it here...
(extasy-test)Iains-MacBook-Pro:grlsd-on-archer ibethune$ RADICAL_ENMD_VERBOSE=Report python extasy_gromacs_lsdmap.py --RPconfig archer.rcfg --Kconfig gromacslsdmap.wcfg

================================================================================
 EnsembleMD (0.3.14-1-g46723d4)                                                 
================================================================================

Starting Allocation                                                           ok
        Verifying pattern                                                     ok
        Starting pattern execution                                            ok
--------------------------------------------------------------------------------
Executing simulation-analysis loop with 1 iterations on 24 allocated core(s) on 'epsrc.archer'

Job waiting on queue...
```

**Comment by vivek-bala** [comment]
Sorry about missing this one. This should be fixed now.

**Comment by vivek-bala** [comment]
master + extasy_0.2-devel branches,

**Comment by vivek-bala** [comment]
plus I think I'll rename extasy_0.2-devel branch to extasy_data or extasy_docs_data. The naming is confusing.

**Comment by ibethune** [comment]
Thanks, this is working correctly now.  Any reason why the example files etc. can't live in the master branch?  Seems to me having one less branch would be less confusing?

**Comment by vivek-bala** [comment]
Example files are on both the master and extasy_data. extasy_data exists mainly to hold the tarballs.

**Comment by vivek-bala** [comment]
I'm happy to move the tarballs to master as well.. but it was previously suggested to keep the tarballs in a separate branch.

**Comment by ibethune** [comment]
I think it's OK as is - as long as we keep the two branches in sync.

**Comment by vivek-bala** [comment]
Yup
