### ISSUE TITLE
ExTASY 0.2 tutorial files have moved?

### ISSUE THREAD

**Issue by CharlieLaughton** [radical-cybertools/ExTASY#227]
Trying a fresh work-through the ExTASY 0.2 tutorial to run an Amber/CoCo job on Archer at http://extasy.readthedocs.org/en/extasy_0.2/pages/coam.html, I hit a problem at Step 2:
```
[ExTASY-tools] charlie@homer 179 % curl -k -O  https://raw.githubusercontent.com/radical-cybertools/ExTASY/extasy_0.2-devel/tarballs/coam-on-archer.tar.gz
[ExTASY-tools] charlie@homer 180% tar xvfz coam-on-archer.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[ExTASY-tools] charlie@homer 181% more coam-on-archer.tar.gz
Not Found
[ExTASY-tools] charlie@homer 182% 
```
Has the location of the tarballs changed?

**Comment by vivek-bala** [comment]
Sry about that .. I renamed the branch to extasy_data. The docs should be updated now.

**Comment by CharlieLaughton** [comment]
By “…should be updated now” do you mean “you should find they are now updated”, or “now someone should update them”?  Only at the moment they seem the same as before…

**Comment by vivek-bala** [comment]
Oops.. sry for the confusion. Meant to say I have updated them now. The link seems to be updated in latest docs: http://extasy.readthedocs.org/en/latest/pages/coam.html#running-on-stampede

**Comment by CharlieLaughton** [comment]
Thanks! I have checked and can confirm that all now seems fine.

**Comment by vivek-bala** [comment]
Thanks for checking !
