### ISSUE TITLE
Understanding the logic of run.py in gromacs_lsdmap

### ISSUE THREAD

**Issue by dotsdl** [radical-cybertools/ExTASY#229]
After running the example `gromacs_lsdmap` job and looking at the outputs on stampede, I noticed that the simulation compute units produce a ton of files:

    confout.gro       #confout.gro.6#   #ener.edr.53#  #md.log.46#     #mdout.mdp.4#                      #topol.tpr.24#  #traj.trr.18#
    #confout.gro.1#   #confout.gro.60#  #ener.edr.54#  #md.log.47#     #mdout.mdp.40#                     #topol.tpr.25#  #traj.trr.19#
    #confout.gro.10#  #confout.gro.61#  #ener.edr.55#  #md.log.48#     #mdout.mdp.41#                     #topol.tpr.26#  #traj.trr.2#
    #confout.gro.11#  #confout.gro.62#  #ener.edr.56#  #md.log.49#     #mdout.mdp.42#                     #topol.tpr.27#  #traj.trr.20#
    #confout.gro.12#  #confout.gro.7#   #ener.edr.57#  #md.log.5#      #mdout.mdp.43#                     #topol.tpr.28#  #traj.trr.21#
    #confout.gro.13#  #confout.gro.8#   #ener.edr.58#  #md.log.50#     #mdout.mdp.44#                     #topol.tpr.29#  #traj.trr.22#
    #confout.gro.14#  #confout.gro.9#   #ener.edr.59#  #md.log.51#     #mdout.mdp.45#                     #topol.tpr.3#   #traj.trr.23#
    #confout.gro.15#  ener.edr          #ener.edr.6#   #md.log.52#     #mdout.mdp.46#                     #topol.tpr.30#  #traj.trr.24#
    #confout.gro.16#  #ener.edr.1#      #ener.edr.60#  #md.log.53#     #mdout.mdp.47#                     #topol.tpr.31#  #traj.trr.25#
    #confout.gro.17#  #ener.edr.10#     #ener.edr.61#  #md.log.54#     #mdout.mdp.48#                     #topol.tpr.32#  #traj.trr.26#
    #confout.gro.18#  #ener.edr.11#     #ener.edr.62#  #md.log.55#     #mdout.mdp.49#                     #topol.tpr.33#  #traj.trr.27#
    #confout.gro.19#  #ener.edr.12#     #ener.edr.7#   #md.log.56#     #mdout.mdp.5#                      #topol.tpr.34#  #traj.trr.28#
    #confout.gro.2#   #ener.edr.13#     #ener.edr.8#   #md.log.57#     #mdout.mdp.50#                     #topol.tpr.35#  #traj.trr.29#
    #confout.gro.20#  #ener.edr.14#     #ener.edr.9#   #md.log.58#     #mdout.mdp.51#                     #topol.tpr.36#  #traj.trr.3#
    #confout.gro.21#  #ener.edr.15#     grompp.mdp     #md.log.59#     #mdout.mdp.52#                     #topol.tpr.37#  #traj.trr.30#
    #confout.gro.22#  #ener.edr.16#     md.log         #md.log.6#      #mdout.mdp.53#                     #topol.tpr.38#  #traj.trr.31#
    #confout.gro.23#  #ener.edr.17#     #md.log.1#     #md.log.60#     #mdout.mdp.54#                     #topol.tpr.39#  #traj.trr.32#
    #confout.gro.24#  #ener.edr.18#     #md.log.10#    #md.log.61#     #mdout.mdp.55#                     #topol.tpr.4#   #traj.trr.33#
    #confout.gro.25#  #ener.edr.19#     #md.log.11#    #md.log.62#     #mdout.mdp.56#                     #topol.tpr.40#  #traj.trr.34#
    #confout.gro.26#  #ener.edr.2#      #md.log.12#    #md.log.7#      #mdout.mdp.57#                     #topol.tpr.41#  #traj.trr.35#
    #confout.gro.27#  #ener.edr.20#     #md.log.13#    #md.log.8#      #mdout.mdp.58#                     #topol.tpr.42#  #traj.trr.36#
    #confout.gro.28#  #ener.edr.21#     #md.log.14#    #md.log.9#      #mdout.mdp.59#                     #topol.tpr.43#  #traj.trr.37#
    #confout.gro.29#  #ener.edr.22#     #md.log.15#    mdout.mdp       #mdout.mdp.6#                      #topol.tpr.44#  #traj.trr.38#
    #confout.gro.3#   #ener.edr.23#     #md.log.16#    #mdout.mdp.1#   #mdout.mdp.60#                     #topol.tpr.45#  #traj.trr.39#
    #confout.gro.30#  #ener.edr.24#     #md.log.17#    #mdout.mdp.10#  #mdout.mdp.61#                     #topol.tpr.46#  #traj.trr.4#
    #confout.gro.31#  #ener.edr.25#     #md.log.18#    #mdout.mdp.11#  #mdout.mdp.62#                     #topol.tpr.47#  #traj.trr.40#
    #confout.gro.32#  #ener.edr.26#     #md.log.19#    #mdout.mdp.12#  #mdout.mdp.7#                      #topol.tpr.48#  #traj.trr.41#
    #confout.gro.33#  #ener.edr.27#     #md.log.2#     #mdout.mdp.13#  #mdout.mdp.8#                      #topol.tpr.49#  #traj.trr.42#
    #confout.gro.34#  #ener.edr.28#     #md.log.20#    #mdout.mdp.14#  #mdout.mdp.9#                      #topol.tpr.5#   #traj.trr.43#
    #confout.gro.35#  #ener.edr.29#     #md.log.21#    #mdout.mdp.15#  out.gro                            #topol.tpr.50#  #traj.trr.44#
    #confout.gro.36#  #ener.edr.3#      #md.log.22#    #mdout.mdp.16#  radical_pilot_cu_launch_script.sh  #topol.tpr.51#  #traj.trr.45#
    #confout.gro.37#  #ener.edr.30#     #md.log.23#    #mdout.mdp.17#  run.py                             #topol.tpr.52#  #traj.trr.46#
    #confout.gro.38#  #ener.edr.31#     #md.log.24#    #mdout.mdp.18#  run.sh                             #topol.tpr.53#  #traj.trr.47#
    #confout.gro.39#  #ener.edr.32#     #md.log.25#    #mdout.mdp.19#  start.gro                          #topol.tpr.54#  #traj.trr.48#
    #confout.gro.4#   #ener.edr.33#     #md.log.26#    #mdout.mdp.2#   state.cpt                          #topol.tpr.55#  #traj.trr.49#
    #confout.gro.40#  #ener.edr.34#     #md.log.27#    #mdout.mdp.20#  state_prev.cpt                     #topol.tpr.56#  #traj.trr.5#
    #confout.gro.41#  #ener.edr.35#     #md.log.28#    #mdout.mdp.21#  STDERR                             #topol.tpr.57#  #traj.trr.50#
    #confout.gro.42#  #ener.edr.36#     #md.log.29#    #mdout.mdp.22#  STDOUT                             #topol.tpr.58#  #traj.trr.51#
    #confout.gro.43#  #ener.edr.37#     #md.log.3#     #mdout.mdp.23#  topol.top                          #topol.tpr.59#  #traj.trr.52#
    #confout.gro.44#  #ener.edr.38#     #md.log.30#    #mdout.mdp.24#  topol.tpr                          #topol.tpr.6#   #traj.trr.53#
    #confout.gro.45#  #ener.edr.39#     #md.log.31#    #mdout.mdp.25#  #topol.tpr.1#                      #topol.tpr.60#  #traj.trr.54#
    #confout.gro.46#  #ener.edr.4#      #md.log.32#    #mdout.mdp.26#  #topol.tpr.10#                     #topol.tpr.61#  #traj.trr.55#
    #confout.gro.47#  #ener.edr.40#     #md.log.33#    #mdout.mdp.27#  #topol.tpr.11#                     #topol.tpr.62#  #traj.trr.56#
    #confout.gro.48#  #ener.edr.41#     #md.log.34#    #mdout.mdp.28#  #topol.tpr.12#                     #topol.tpr.7#   #traj.trr.57#
    #confout.gro.49#  #ener.edr.42#     #md.log.35#    #mdout.mdp.29#  #topol.tpr.13#                     #topol.tpr.8#   #traj.trr.58#
    #confout.gro.5#   #ener.edr.43#     #md.log.36#    #mdout.mdp.3#   #topol.tpr.14#                     #topol.tpr.9#   #traj.trr.59#
    #confout.gro.50#  #ener.edr.44#     #md.log.37#    #mdout.mdp.30#  #topol.tpr.15#                     traj.trr        #traj.trr.6#
    #confout.gro.51#  #ener.edr.45#     #md.log.38#    #mdout.mdp.31#  #topol.tpr.16#                     #traj.trr.1#    #traj.trr.60#
    #confout.gro.52#  #ener.edr.46#     #md.log.39#    #mdout.mdp.32#  #topol.tpr.17#                     #traj.trr.10#   #traj.trr.61#
    #confout.gro.53#  #ener.edr.47#     #md.log.4#     #mdout.mdp.33#  #topol.tpr.18#                     #traj.trr.11#   #traj.trr.62#
    #confout.gro.54#  #ener.edr.48#     #md.log.40#    #mdout.mdp.34#  #topol.tpr.19#                     #traj.trr.12#   #traj.trr.7#
    #confout.gro.55#  #ener.edr.49#     #md.log.41#    #mdout.mdp.35#  #topol.tpr.2#                      #traj.trr.13#   #traj.trr.8#
    #confout.gro.56#  #ener.edr.5#      #md.log.42#    #mdout.mdp.36#  #topol.tpr.20#                     #traj.trr.14#   #traj.trr.9#
    #confout.gro.57#  #ener.edr.50#     #md.log.43#    #mdout.mdp.37#  #topol.tpr.21#                     #traj.trr.15#
    #confout.gro.58#  #ener.edr.51#     #md.log.44#    #mdout.mdp.38#  #topol.tpr.22#                     #traj.trr.16#
    #confout.gro.59#  #ener.edr.52#     #md.log.45#    #mdout.mdp.39#  #topol.tpr.23#                     #traj.trr.17#

Each compute unit *should* correspond to a single simulation, so it doesn't make much sense that all these files are generated. Looking more closely at the contents of `gromacs_lsdmap`'s [`run.py`](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/helper_scripts/run.py) helper script, I noticed that it is indeed running a series of simulations. Is this the intended behavior? I suppose in this way each compute unit runs an instance of every starting frame individually, but I still don't understand why this is desired.

**Comment by dotsdl** [comment]
Ah...I *think* I see now. The number of simulations is decided by the number of frames in the starting gro file, correct? These are then distributed over however many compute units one has specified. I can see how this makes a bit more sense now, but it wasn't obvious from the set of scripts alone.

**Comment by dotsdl** [comment]
Btw...what exactly does the [`run.sh`](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/inp_files/run.sh) script among the `inp_files` actually do? I can't find where it is called anywhere, but deleting it does appear to make the example run fail.

**Comment by vivek-bala** [comment]
Your understanding is correct. The simulations are divided uniformly into each task. 1000 simulations with 10 tasks would mean 100 simulations/task. The idea was to keep this for these examples and short running jobs so that we are able to run say 10K, 100K simulations. But we will have another example soon where there would be 1 simulation/task (this would also give us more control).

**Comment by vivek-bala** [comment]
```run.py``` is the python wrapper which creates the bash script ```run.sh``` which extracts 1 frame at a time from .gro file of the corresponding task and runs the simulation. You would find the ```run.sh``` file in each task folder (unit.00* on the remote machine).

**Comment by vivek-bala** [comment]
I just noticed the ```run.sh``` in the inp_files folder. That shouldn't be there, I think it got pushed from one of the experiments. Deleted now. Sry for the confusion.

**Comment by dotsdl** [comment]
Not a problem. Thanks for the quick reply! I'm poking around pretty hard on this to get it working for my own systems as well as to figure out how to do more complex things with the framework. It's quite cool!
