### ISSUE TITLE
What's the best way to upload directories as input data?

### ISSUE THREAD

**Issue by dotsdl** [radical-cybertools/ExTASY#230]
Uploading directories by adding them to the `Kernel.upload_input_data` list does not appear to work. If this is the expected behavior, what are the suggested ways around it? 

I'm interested because running my gromacs jobs with LSDmap requires a custom set of forcefield files. For this particular case I could just upload them once to stampede and then have the Kernel link to them, but I was interested in an alternative for future reference.

**Comment by vivek-bala** [comment]
1) Currently, folder transfer is not supported in RP (therefore not in ensemblemd too). There is now a feature request in RP for this (https://github.com/radical-cybertools/radical.pilot/issues/936).

2) If the requirement is to stage all the files ONLY once, you can stage the files once by using the kernel in the ```pre_loop``` stage. You can then refer to these files using ```$PRE_LOOP``` in the simulation/analysis stages.

**Comment by vivek-bala** [comment]
Moved to BB: https://bitbucket.org/extasy-project/extasy-workflows/issues/19/ability-to-upload-folders
