### ISSUE TITLE
Changing 'num_cores_per_sim_cu' for LSDmap does not change threads used per simulation

### ISSUE THREAD

**Issue by dotsdl** [radical-cybertools/ExTASY#231]
In the [`gromacslsdmap.wcfg`](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/gromacslsdmap_on_stampede.wcfg) configuration file, one can specify how many [cores are used per simulation cu](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/gromacslsdmap_on_stampede.wcfg#L12). However, no matter the value this is set to (along with an appropriate change to [`num_CUs`](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/gromacslsdmap_on_stampede.wcfg#L6)), the number of threads each [`gmx mdrun`](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/helper_scripts/run.py#L45) instance uses is always 1.

**Comment by dotsdl** [comment]
Also, though I realize this is at the level of `radical.pilot`, if on stampede one sets a multiple of 16 for the number of cores each CU should get for a pilot with, say, 512 cores, is there anything built in to guarantee each node will be in use by only one CU? That is, CUs won't be using cores randomly across the allocation?

**Comment by andre-merzky** [comment]
I can't answer the  first part, but only the second: the way the scheduler is written happens to result in one CU per node for stampede (for `cores=16`).  That should be considered coincidental, and may change at some point.  What *should* happen is that MPI units are allowed to cross node boundaries, and threaded units (or non-MPI in general I guess) are confined to live within a node.

FWIW, here is the current scheduler definition as used in the stampede configuration:

https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/agent/radical-pilot-agent-multicore.py#L800

HtH, Andre.

**Comment by dotsdl** [comment]
@andre-merzky thanks for that clarification! There are actually performance benefits one can take advantage of by knowing only a single CU is on a node; for example, with gromacs `mdrun` one can pin a thread to each core, and this can be a pretty good speedup. If this isn't something that sticks around it's not the end of the world, but it is something to consider.

**Comment by vivek-bala** [comment]
I think that's expected. Two reasons:

1) The default executable is non mpi ("gmx mdrun" as opposed to "gmx_mpi
mdrun"). This is specified in the run.py file

2) The wrapper " run.py" would have to handle allocation of cores
currently. By default it launches over single cores.

**Comment by dotsdl** [comment]
Ah okay, but then what is `num_cores_per_sim_cu` supposed to do? I imagine it should change the number of cores used by the `gromacs` kernel, with

    gromacs.cores = Kconfig.num_cores_per_sim_cu

in [`extasy_gromacs_lsdmap_loop.py`](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/extasy_gromacs_lsdmap_loop.py#L77). But then one should probably not set `-nt` in the `mdrun` call of `run.py`. Working on this now to see if I can't get it working.

I'm using a build of gromacs with `gmx_mpi`, so this *should* all work.

**Comment by dotsdl** [comment]
After a bit of struggle, I've realized (took me long enough) that doing what I want with mdrun usage of MPI will require splitting the TPR building and running the MD itself into two separate kernels.

**Comment by vivek-bala** [comment]
I agree, with the current implementation. ```num_cores_per_sim_cu``` is confusing and not required. I have removed them now. Thanks.
