### ISSUE TITLE
`grompp_options` and `mdrun_options` not passed to run script in LSDmap

### ISSUE THREAD

**Issue by dotsdl** [radical-cybertools/ExTASY#232]
The [`grompp_options` and `mdrun_options` parameters](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/gromacslsdmap_on_stampede.wcfg#L17-L18) are not passed to the run script generated by [`run.py`](https://github.com/radical-cybertools/ExTASY/blob/master/examples/gromacs_lsdmap/helper_scripts/run.py).

**Comment by vivek-bala** [comment]
I have updated the scripts now. Please try again.

**Comment by vivek-bala** [comment]
duplicate #234
