### ISSUE TITLE
Bluewaters workflows configuration

### ISSUE THREAD

**Issue by ashkurti** [radical-cybertools/ExTASY#245]
1. Is there any mongodb url that we could use with bluewaters resource configuration file for the extasy workflows.
2. Has anyone managed to setup a passwordless connection to bluewaters from any remote machine (given the 30 seconds tokens that make part of the password).
3. What is the scenario of the lsdmap gromacs workflows that run on bluewaters - or aren't they running yet - in relation to my questions 1 and 2.

Thanks to anyone who can answer this.

**Comment by marksantcroos** [comment]
> Is there any mongodb url that we could use with bluewaters resource configuration file for the extasy workflows.

Any will do.

> Has anyone managed to setup a passwordless connection to bluewaters from any remote machine (given the 30 seconds tokens that make part of the password).

You want to get a x509 proxy through myproxy and use gsissh to connect to bluewaters. In that way, you will only need to use the keyfob once a week.

**Comment by ashkurti** [comment]
@marksantcroos thanks for your answer and can you be more specific for both cases please with any examples for answer 1 and any links & examples for answer 2. Thanks.

**Comment by vivek-bala** [comment]
1) You can use the default epcc mongodb url from any of the configuration files (eg: https://bitbucket.org/extasy-project/extasy-workflows/src/83245a4969b5e5a68e72b39e46153ca4ee5d790d/examples/coam-on-stampede/stampede.rcfg?at=master&fileviewer=file-view-default#stampede.rcfg-9).

2) Following https://bluewaters.ncsa.illinois.edu/getting-started/#Logging worked for me. 

You can specify the duration for the certificate to be used (I believe the maximum in 168 hours).
`myproxy-logon -s tfca.ncsa.illinois.edu -l <username> -t <duration in hours>`
You should then be able to ssh as you would do for other machines.

PS: Please create all new issues in (/ use examples from) the bitbucket repository (https://bitbucket.org/extasy-project/extasy-workflows) as this repository is deprecated.

**Comment by vivek-bala** [comment]
As stated in the dev call today, this is resolved.
